/**
 * THE BASELINE: how many database statements still read a tenant-owned table
 * without naming a tenant, per file, as of the tenancy migration.
 *
 * This is not a target and it is not acceptable - it is a MEASUREMENT, taken so
 * that the number can only ever go down. query-guard.test.ts fails when a file
 * exceeds its number here, or when a file that is not listed grows one. Phases two
 * to four rewrite these query sites; each one that gets a tenant filter comes off
 * this list, and when the list is empty the guard becomes an absolute rule and this
 * file can be deleted.
 *
 * Every write site is already absent, and not by discipline: tenant_id is NOT NULL,
 * so an insert that forgets it does not compile.
 *
 * Generated by scanning the source. Do not hand-edit upwards.
 */
export const UNSCOPED_BASELINE: Record<string, number> = {
	// ai-agent/knowledge.ts and campaigns/outcome.ts are ABSENT ON PURPOSE: the AI
	// phase scoped every read in both. knowledge.ts is raw `db.execute(sql\`...\`)`
	// that this scanner cannot judge either way, so its tenant term is guarded by
	// lib/ai-agent/knowledge.tenant.test.ts, which compiles the two fragments and
	// asserts tenant_id is in the SQL and the tenant in the parameters.
	//
	// dialer.ts keeps ONE, and it is a decision, not a leftover. The dialer is a timer:
	// nobody is logged in, so there is no request to take a tenant from. Exactly two of
	// its reads are platform-wide on purpose - "which campaigns are running" and the
	// sweep for abandoned `calling` claims - because one dialer process serves every
	// customer and an orphaned claim has to be rescued whoever owns it. Both carry each
	// row's own tenant_id forward into everything they then do, and the scanner sees
	// one of the two. Every other statement in the file names a tenant taken from the
	// campaign row. See the file header.
	// tenant-config.ts keeps ONE, and it is the only read in the platform that is
	// SUPPOSED to see every customer at once: it generates Asterisk's configuration, so
	// it reads every tenant's operator extensions in one query and then splits them by
	// tenant_id into one config block per customer. Scoping it would mean generating the
	// config one tenant at a time and reloading Asterisk once per customer, and the
	// output is a file nobody can read without being root on the PBX host - not an HTTP
	// response. Every extension it emits is named `<slug>-<ext>` from the row's own
	// tenant, which is the property tenant-config.test.ts checks directly.
	"lib/asterisk/tenant-config.ts": 1,
	"lib/campaigns/dialer.ts": 1,
	"lib/integrations/notifications/monitor.ts": 2,
	// contact-matcher and transfer are ABSENT ON PURPOSE: the calls/telephony phase
	// scoped every read in both, the caller-history reads included - those two are the
	// ones the AGENT SPEAKS, so an unscoped ticket subject would have been read out loud
	// to the wrong company's caller. Allowed zero from here on.
	//
	// crm-writer keeps ONE, and it is the limit of a textual scan rather than a finding:
	// the ai_sessions upsert passes a `values` object assembled a few lines earlier and
	// the tenant is in THAT object - the call's own tenant_id, read inside the writing
	// statement and required to match the tenant the caller named. Every other statement
	// in the file names the tenant explicitly, and the compiler guarantees the write.
	"lib/telephony/crm-writer.ts": 1,
	// ai-agent, ai-assistant and ai-costs are ABSENT ON PURPOSE: the AI phase scoped all
	// 22 of their reads, joins included - every leg of the ai_sessions -> calls ->
	// contacts / ai_analyses joins carries the tenant, not only the driving table.
	// Allowed zero from here on.
	// ai-analyses and asterisk are ABSENT ON PURPOSE: the calls/telephony phase scoped
	// all 26 of their reads. On the asterisk routes that included the two writes a body
	// could aim at another customer - transfer and hangup now check the call's tenant
	// before Asterisk is asked anything at all.
	// audit-logs is ABSENT ON PURPOSE: the staff phase scoped both of its statements
	// (the page and its count share one tenantWhere clause), so it is allowed zero and
	// the next unscoped read added to it fails outright.
	//
	// auth keeps FOUR, and every one of them is a decision rather than a leftover.
	// users.phone is unique PLATFORM-WIDE because the login form is a phone and a
	// password with no tenant field, so these four ask "which single account is this" -
	// a question that has no tenant to filter by, and whose ANSWER is what supplies the
	// tenant for the token. They are: register's "is this login taken anywhere" probe,
	// login's lookup, refresh's Redis-owner lookup, and refresh's legacy scan (which can
	// only match the exact opaque token the caller already holds). Scoping any of them
	// would mean taking the tenant from client input, which is the leak itself.
	"routes/auth/auth.handlers.ts": 4,
	// bookings, contacts, dashboard (both files), follow-ups, reports and tickets are
	// ABSENT ON PURPOSE, not forgotten: the CRM phase rewrote all 94 of their reads
	// and the scanner now finds zero in them. An absent file is allowed zero, so the
	// ratchet is an absolute rule for those six - the next unscoped read added to any
	// of them fails the test instead of fitting under a number.
	// calls (both files) is ABSENT ON PURPOSE: all 33 reads are scoped, and so is every
	// JOIN leg and both correlated EXISTS subqueries behind the "has a recording / has a
	// transcript" columns - a join scoped on one side only is the hole this scanner
	// cannot see, and the /calls list is the platform's most-read screen.
	// campaigns (both files) and knowledge-base are ABSENT ON PURPOSE: all 43 reads are
	// scoped. Where a page and its total shared a `where` variable the tenant is now
	// written out at BOTH statements - the filter list stays shared so the two ask the
	// same question, but neither can lose the tenant to an edit one screen away.
	// live-calls is ABSENT ON PURPOSE: its five reads are scoped, and the board itself is
	// filtered in the orchestrator's in-memory map, where no WHERE clause can help -
	// listActiveCalls(tenantId) and friends take the tenant as a required argument. See
	// lib/telephony/call-orchestrator.tenancy.test.ts.
	// operator-profiles is ABSENT ON PURPOSE: all 18 are scoped, including the extension
	// uniqueness probes, which are scoped BECAUSE the index is - UNIQUE (tenant_id,
	// extension). Allowed zero from here on.
	// transcripts is ABSENT ON PURPOSE: all nine reads are scoped, the CSV/text exports
	// included, and the single call lookup every handler goes through is what stops the
	// append endpoint stamping the CALLER's tenant onto another customer's call.
	// users keeps ONE: the phone-uniqueness probe in updateHandler, unscoped for the same
	// reason auth's four are (see above) - it asks the platform-wide question the
	// users_phone_unique index asks, so that a collision is a clean 409 rather than a 500.
	"routes/users/users.handlers.ts": 1,
	// webhooks (the legacy FreePBX pair) is ABSENT ON PURPOSE. They are unauthenticated
	// and their payload carries no tenant, so the tenant is getSoleTenantId() - which
	// throws rather than guessing once a second customer exists - and every read AND the
	// call-end UPDATE are scoped to it. Scoping the update is what turns "an anonymous
	// request can finalise any customer's call by id" into that same loud throw.
};

/** The total, asserted separately so a file rename cannot hide a regression. */
export const UNSCOPED_BASELINE_TOTAL = 314;
