export const ErrorCode = {
	// Validation
	VALIDATION_ERROR: "VALIDATION_ERROR",
	INVALID_INPUT: "INVALID_INPUT",
	MISSING_FIELD: "MISSING_FIELD",
	INVALID_FORMAT: "INVALID_FORMAT",

	// Authentication
	UNAUTHORIZED: "UNAUTHORIZED",
	INVALID_TOKEN: "INVALID_TOKEN",
	TOKEN_EXPIRED: "TOKEN_EXPIRED",
	INVALID_CREDENTIALS: "INVALID_CREDENTIALS",

	// Authorization
	FORBIDDEN: "FORBIDDEN",
	INSUFFICIENT_PERMISSIONS: "INSUFFICIENT_PERMISSIONS",
	ACCESS_DENIED: "ACCESS_DENIED",

	// Not Found
	NOT_FOUND: "NOT_FOUND",
	RESOURCE_NOT_FOUND: "RESOURCE_NOT_FOUND",
	USER_NOT_FOUND: "USER_NOT_FOUND",
	SCHOOL_NOT_FOUND: "SCHOOL_NOT_FOUND",

	// Conflict
	CONFLICT: "CONFLICT",
	ALREADY_EXISTS: "ALREADY_EXISTS",
	DUPLICATE_ENTRY: "DUPLICATE_ENTRY",

	// Business Logic
	UNPROCESSABLE_ENTITY: "UNPROCESSABLE_ENTITY",
	BUSINESS_RULE_VIOLATION: "BUSINESS_RULE_VIOLATION",
	INVALID_OPERATION: "INVALID_OPERATION",
	INVALID_STATE: "INVALID_STATE",

	// Rate Limiting
	RATE_LIMIT_EXCEEDED: "RATE_LIMIT_EXCEEDED",

	// Server Errors
	INTERNAL_ERROR: "INTERNAL_ERROR",
	DATABASE_ERROR: "DATABASE_ERROR",
	EXTERNAL_SERVICE_ERROR: "EXTERNAL_SERVICE_ERROR",
} as const;

export type ErrorCodeType = (typeof ErrorCode)[keyof typeof ErrorCode];

export interface ErrorDetails {
	field?: string;
	reason?: string;
	[key: string]: unknown;
}
